/*
 * File: app/view/GroupParam_PropertyForm.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('QueryBuilder.view.GroupParam_PropertyForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox'
    ],

    height: 399,
    itemId: 'GroupParam_PropertyForm',
    width: 615,
    layout: 'border',
    title: 'Свойства группы условий запроса',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    region: 'center',
                    autoScroll: true,
                    bodyPadding: 16,
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            itemId: 'GroupCondition',
                            fieldLabel: 'Операция для связи условий',
                            labelWidth: 180,
                            editable: false,
                            store: [
                                'and',
                                'or',
                                'exists'
                            ],
                            listeners: {
                                change: {
                                    fn: me.onConditionChange,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'checkboxfield',
                            handler: function(checkbox, checked) {
                                var GroupParam_PropertyForm = checkbox.findParentByType('#GroupParam_PropertyForm');
                                GroupParam_PropertyForm.rawData.NOT_GroupCondition=checked;
                                var DesignMainContainer=checkbox. findParentByType('#DesignMainContainer');
                                DesignMainContainer.modified=true;

                            },
                            anchor: '100%',
                            itemId: 'NOT_GroupCondition',
                            fieldLabel: '',
                            boxLabel: 'Добавить отрицание для группы условий'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onConditionChange: function(field, newValue, oldValue, eOpts) {
         this.rawData.GroupCondition=newValue;
        var DesignMainContainer=field. findParentByType('#DesignMainContainer');
                    DesignMainContainer.modified=true;

    },

    LoadNodeValues: function(rawData, record) {
        this.rawData = rawData;
        var mainContainer = this.findParentByType('#DesignMainContainer');
        //this.down('#').setValue(rawData.);
        this.down('#NOT_GroupCondition').setValue(rawData.NOT_GroupCondition);
        this.down('#GroupCondition').setValue(rawData.GroupCondition);

    }

});