/*
 * File: app/view/VisualPanelMaket_H1X1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VisualPanelMakets.view.VisualPanelMaket_H1X1', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.panel.Panel'
    ],

    VisualPanelDescription: 'Горизонтальный сплит 1Х1',
    height: 451,
    width: 729,

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'panel',
                            VisualPanelItem: true,
                            itemId: 'VisualPanelItem1',
                            layout: 'fit',
                            title: 'Выберите представление'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    width: '',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'panel',
                            VisualPanelItem: true,
                            itemId: 'VisualPanelItem2',
                            layout: 'fit',
                            title: 'Выберите представление'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});