/*
 * File: app/view/VisualPanelMaket_H2V2.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('VisualPanelMakets.view.VisualPanelMaket_H2V2', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.panel.Panel'
    ],

    VisualPanelMaket: false,
    VisualPanelDescription: 'bhdgfhdhgdgh',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    region: 'north',
                    split: true,
                    itemId: 'Container_Top',
                    layout: 'border',
                    items: [
                        {
                            xtype: 'panel',
                            VisualPanelItem: true,
                            flex: 1,
                            region: 'west',
                            split: true,
                            itemId: 'Panel_TL',
                            title: 'My Panel'
                        },
                        {
                            xtype: 'panel',
                            VisualPanelItem: true,
                            flex: 1,
                            region: 'center',
                            split: true,
                            itemId: 'Panel_TR',
                            title: 'My Panel'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    region: 'center',
                    split: true,
                    itemId: 'Container_Bottom',
                    layout: 'border',
                    items: [
                        {
                            xtype: 'panel',
                            VisualPanelItem: true,
                            flex: 1,
                            region: 'west',
                            split: true,
                            itemId: 'Panel_BL',
                            title: 'My Panel'
                        },
                        {
                            xtype: 'panel',
                            VisualPanelItem: true,
                            flex: 1,
                            region: 'center',
                            itemId: 'Panel_BR',
                            title: 'My Panel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});