/*
 * File: app/view/chart_PropertyForm.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DiagramTemplate.view.chart_PropertyForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.Trigger',
        'Ext.panel.Panel',
        'Ext.form.field.TextArea',
        'Ext.panel.Tool'
    ],

    height: 471,
    id: 'chart_PropertyForm',
    itemId: 'chart_PropertyForm',
    width: 648,
    autoScroll: true,
    bodyPadding: 10,
    title: 'Свойства ряда данных',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'Edt_description',
                    fieldLabel: 'Наименование',
                    listeners: {
                        change: {
                            fn: me.onEdt_descriptionChange2,
                            scope: me
                        }
                    }
                },
                me.processEdt_chart_color({
                    xtype: 'triggerfield',
                    itemId: 'Edt_chart_color',
                    fieldLabel: 'Цвет',
                    labelWidth: 35,
                    emptyText: 'Выбор цвета',
                    regex: /^[0-9a-f]{3,6}$/i,
                    selectOnFocus: true,
                    triggerCls: 'x-form-search-trigger',
                    listeners: {
                        change: {
                            fn: me.onEdt_description3Change,
                            scope: me
                        }
                    }
                }),
                {
                    xtype: 'container',
                    border: '',
                    margin: 4,
                    layout: {
                        type: 'hbox',
                        align: 'bottom',
                        pack: 'end'
                    }
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    layout: 'fit',
                    title: 'Текст SQL-запроса',
                    items: [
                        {
                            xtype: 'textareafield',
                            itemId: 'EdtSQL',
                            fieldLabel: '',
                            labelWidth: 120,
                            listeners: {
                                change: {
                                    fn: me.onEdtSQLChange,
                                    scope: me
                                }
                            }
                        }
                    ],
                    tools: [
                        {
                            xtype: 'tool',
                            type: 'maximize',
                            listeners: {
                                click: {
                                    fn: me.onToolClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processEdt_chart_color: function(config) {
        config.onTriggerClick = function (evnt) {
            if(this.disabled){
                return;
            }
            var me = this;
            this.menu = new Ext.menu.ColorPicker({
                shadow: true,
                autoShow : true,
                listeners: {
                    scope:this,
                    select: function(field, value, opts){
                        me.setValue(value);
                        me.inputEl.setStyle({backgroundColor: '#' +me.getValue(), backgroundImage: 'none'});
                        me.menu.hide();
                    },
                    show: function(field,opts){
                        field.getEl().monitorMouseLeave(500, field.hide, field);
                    }
                }
            });
            this.menu.alignTo(this.inputEl, 'tl-bl?');
            this.menu.doLayout();

            this.menu.on(Ext.apply({}, this.menuListeners, {
                scope:this
            }));

            this.menu.show(this.inputEl);

        };
        return config;
    },

    onEdt_descriptionChange2: function(field, newValue, oldValue, eOpts) {
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
        this.rawData.Description=newValue;
        if(this.needUpdateTree==true){
            if(trim(this.rawData.Description)=='')
                this.record.set('text', mainContainer.MICaption_Chart);
            else
                this.record.set('text', this.rawData.Description);
            this.record.commit();
            this.rawData.text=this.rawData.Description;
        }
    },

    onEdt_description3Change: function(field, newValue, oldValue, eOpts) {
        this.rawData.chart_color=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onEdtSQLChange: function(field, newValue, oldValue, eOpts) {
        this.rawData.SQL=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onToolClick: function(tool, e, eOpts) {
        var chart_PropertyForm=tool.findParentByType('#chart_PropertyForm');

        SQLEditor(chart_PropertyForm.down('#EdtSQL').getValue(),function(SQLText)
                  {
                      chart_PropertyForm.down('#EdtSQL').setValue(SQLText);
                      //table_PropertyForm.rawData.SQL=SQLText;
                  }
                 );

    },

    LoadNodeValues: function(rawData, record) {
        this.needUpdateTree=false; //нужно для отключения переписывания текста в дереве при присвоении значений текста
        this.rawData=rawData;
        this.record = record;
        this.down('#Edt_description').setValue(rawData.Description);
        this.down('#EdtSQL').setValue(rawData.SQL);
        var _Edt_chart_color=this.down('#Edt_chart_color');
        _Edt_chart_color.setValue(rawData.chart_color);
        _Edt_chart_color.inputEl.setStyle({backgroundColor: '#' +_Edt_chart_color.getValue(), backgroundImage: 'none',color:'#' +invert(_Edt_chart_color.getValue())});
        this.needUpdateTree=true;
    }

});