/*
 * File: app/view/diagram_PropertyForm.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DiagramTemplate.view.diagram_PropertyForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.panel.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.form.CheckboxGroup',
        'Ext.form.field.Checkbox'
    ],

    height: 602,
    id: 'diagram_PropertyForm',
    itemId: 'diagram_PropertyForm',
    width: 788,
    autoScroll: true,
    title: '',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    title: 'Свойства диаграммы',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.6,
                                    itemId: 'Edt_Code',
                                    margin: 3,
                                    fieldLabel: 'Код диаграммы',
                                    listeners: {
                                        change: {
                                            fn: me.onEdt_descriptionChange1,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.4,
                                    itemId: 'Edt_code_help',
                                    margin: 3,
                                    fieldLabel: 'Код справки',
                                    labelWidth: 80,
                                    listeners: {
                                        change: {
                                            fn: me.onEdt_descriptionChange11,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            border: 2,
                            margin: '0 3 0 3',
                            title: 'Заголовок',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'Edt_description',
                                    margin: '0 3 3 3',
                                    fieldLabel: 'Наименование',
                                    listeners: {
                                        change: {
                                            fn: me.onEdt_descriptionChange,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'fieldset',
                                    flex: 1,
                                    border: 0,
                                    padding: 0,
                                    layout: 'column',
                                    items: [
                                        me.processEdt_header_fill_color({
                                            xtype: 'triggerfield',
                                            columnWidth: 0.35,
                                            itemId: 'Edt_header_fill_color',
                                            margin: '0 3 3 1',
                                            padding: 0,
                                            fieldLabel: 'Цвет фона',
                                            labelWidth: 80,
                                            emptyText: 'Выбор цвета',
                                            regex: /^[0-9a-f]{3,6}$/i,
                                            selectOnFocus: true,
                                            triggerCls: 'x-form-search-trigger',
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_BackgrColorChange113,
                                                    scope: me
                                                }
                                            }
                                        }),
                                        me.processEdt_header_text_color({
                                            xtype: 'triggerfield',
                                            columnWidth: 0.35,
                                            itemId: 'Edt_header_text_color',
                                            margin: '0 3 3 3',
                                            padding: 0,
                                            fieldLabel: 'Цвет текста',
                                            labelWidth: 80,
                                            emptyText: 'Выбор цвета',
                                            regex: /^[0-9a-f]{3,6}$/i,
                                            selectOnFocus: true,
                                            triggerCls: 'x-form-search-trigger',
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_BackgrColorChange1121,
                                                    scope: me
                                                }
                                            }
                                        }),
                                        {
                                            xtype: 'textfield',
                                            columnWidth: 0.3,
                                            itemId: 'Edt_header_font_size',
                                            margin: '0 1 3 3',
                                            fieldLabel: 'Размер шрифта',
                                            emptyText: '12px',
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_descriptionChange111212121,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            border: 2,
                            cls: '',
                            margin: '3 3 0 3',
                            padding: '3 6 3 6',
                            layout: 'column',
                            title: 'Область диаграммы',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    columnWidth: 0.2,
                                    margin: 0,
                                    title: '',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        padding: 3
                                    },
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            itemId: 'Edt_diagram_width',
                                            fieldLabel: 'Ширина',
                                            labelWidth: 50,
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_descriptionChange11121111,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'numberfield',
                                            itemId: 'Edt_diagram_height',
                                            margin: 0,
                                            fieldLabel: 'Высота',
                                            labelWidth: 50,
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_descriptionChange111211111,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    columnWidth: 0.4,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        padding: 3
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            itemId: 'Edt_diagram_type',
                                            fieldLabel: 'Тип',
                                            labelWidth: 30,
                                            editable: false,
                                            displayField: 'name',
                                            store: [
                                                [
                                                    '1',
                                                    'Круговая'
                                                ],
                                                [
                                                    '2',
                                                    'Гистограмма (раздельные столбцы)'
                                                ],
                                                [
                                                    '3',
                                                    'Гистограмма (общие столбцы)'
                                                ],
                                                [
                                                    '4',
                                                    'Линейный график'
                                                ],
                                                [
                                                    '5',
                                                    'График-радар (с заливкой)'
                                                ],
                                                [
                                                    '6',
                                                    'Линейный с областями'
                                                ],
                                                [
                                                    '7',
                                                    'График-радар (без заливки)'
                                                ],
                                                [
                                                    '8',
                                                    'Датчик'
                                                ]
                                            ],
                                            valueField: 'id',
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_descriptionChange1111,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'combobox',
                                            itemId: 'Edt_orientation',
                                            margin: 0,
                                            fieldLabel: 'Ориентация',
                                            labelWidth: 80,
                                            editable: false,
                                            displayField: 'name',
                                            store: [
                                                [
                                                    '0',
                                                    'Книжная'
                                                ],
                                                [
                                                    '1',
                                                    'Альбомная'
                                                ]
                                            ],
                                            valueField: 'id',
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_descriptionChange11112,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    columnWidth: 0.4,
                                    margin: 0,
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch',
                                        padding: 3
                                    },
                                    items: [
                                        me.processEdt_bg_color({
                                            xtype: 'triggerfield',
                                            flex: 1,
                                            itemId: 'Edt_bg_color',
                                            fieldLabel: 'Цвет фона',
                                            labelWidth: 70,
                                            emptyText: 'Выбор цвета',
                                            regex: /^[0-9a-f]{3,6}$/i,
                                            selectOnFocus: true,
                                            triggerCls: 'x-form-search-trigger',
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_BackgrColorChange,
                                                    scope: me
                                                }
                                            }
                                        }),
                                        {
                                            xtype: 'combobox',
                                            itemId: 'Edt_diagram_theme',
                                            margin: 0,
                                            fieldLabel: 'Тема',
                                            labelWidth: 35,
                                            editable: false,
                                            displayField: 'name',
                                            store: [
                                                [
                                                    'Base',
                                                    'Базовая'
                                                ],
                                                [
                                                    'Green',
                                                    'Зеленая'
                                                ],
                                                [
                                                    'Sky',
                                                    'Голубая'
                                                ],
                                                [
                                                    'Red',
                                                    'Красная'
                                                ],
                                                [
                                                    'Purple',
                                                    'Пурпурная'
                                                ],
                                                [
                                                    'Blue',
                                                    'Синяя'
                                                ],
                                                [
                                                    'Yellow',
                                                    'Желтая'
                                                ],
                                                [
                                                    'Category1',
                                                    'Тема 1'
                                                ],
                                                [
                                                    'Category2',
                                                    'Тема 2'
                                                ],
                                                [
                                                    'Category3',
                                                    'Тема 3'
                                                ],
                                                [
                                                    'Category4',
                                                    'Тема 4'
                                                ],
                                                [
                                                    'Category5',
                                                    'Тема 5'
                                                ],
                                                [
                                                    'Category6',
                                                    'Тема 6'
                                                ]
                                            ],
                                            valueField: 'id',
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_descriptionChange11111,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            layout: 'column',
                            title: 'Ряды данных',
                            items: [
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.5,
                                    itemId: 'Edt_gutter',
                                    margin: '0 3 3 0',
                                    fieldLabel: 'Расстояние между рядами данных (%)',
                                    labelWidth: 230,
                                    inputType: 'number',
                                    listeners: {
                                        change: {
                                            fn: me.onEdt_descriptionChange1112,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.5,
                                    itemId: 'Edt_groupGutter',
                                    margin: '0 0 3 3',
                                    fieldLabel: 'Расстояние между элементами ряда (%)',
                                    labelWidth: 245,
                                    inputType: 'number',
                                    listeners: {
                                        change: {
                                            fn: me.onEdt_descriptionChange11122,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            border: 2,
                            margin: 3,
                            padding: '3 6 3 6',
                            layout: 'column',
                            title: 'Подписи на диагрмме',
                            items: [
                                {
                                    xtype: 'combobox',
                                    columnWidth: 0.3,
                                    itemId: 'Edt_label_display',
                                    margin: '0 0 0 3',
                                    fieldLabel: 'Расположение подписи',
                                    labelWidth: 90,
                                    editable: false,
                                    displayField: 'name',
                                    store: [
                                        [
                                            'none',
                                            'Не отображать'
                                        ],
                                        [
                                            'insideStart',
                                            'Внизу внутри'
                                        ],
                                        [
                                            'insideEnd',
                                            'Вверху внутри'
                                        ],
                                        [
                                            'outside',
                                            'Снаружи'
                                        ]
                                    ],
                                    valueField: 'id',
                                    listeners: {
                                        change: {
                                            fn: me.onEdt_descriptionChange11111_12,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'combobox',
                                    columnWidth: 0.3,
                                    itemId: 'Edt_label_type_visible',
                                    margin: '0 0 0 6',
                                    fieldLabel: 'Направление текста',
                                    labelWidth: 80,
                                    editable: false,
                                    displayField: 'name',
                                    store: [
                                        [
                                            'horizontal',
                                            'Горизонтально'
                                        ],
                                        [
                                            'vertical',
                                            'Вертикально'
                                        ]
                                    ],
                                    valueField: 'id',
                                    listeners: {
                                        change: {
                                            fn: me.onEdt_descriptionChange11111_1,
                                            scope: me
                                        }
                                    }
                                },
                                me.processEdt_info_label_color({
                                    xtype: 'triggerfield',
                                    columnWidth: 0.2,
                                    itemId: 'Edt_info_label_color',
                                    margin: '0 0 0 6',
                                    padding: 0,
                                    fieldLabel: 'Цвет шрифта',
                                    labelWidth: 50,
                                    emptyText: 'Выбор цвета',
                                    regex: /^[0-9a-f]{3,6}$/i,
                                    selectOnFocus: true,
                                    triggerCls: 'x-form-search-trigger',
                                    listeners: {
                                        change: {
                                            fn: me.onEdt_BackgrColorChange111,
                                            scope: me
                                        }
                                    }
                                }),
                                {
                                    xtype: 'textfield',
                                    columnWidth: 0.2,
                                    itemId: 'Edt_label_font_size',
                                    margin: '0 3 0 6',
                                    fieldLabel: 'Размер шрифта',
                                    labelWidth: 50,
                                    emptyText: '12px',
                                    listeners: {
                                        change: {
                                            fn: me.onEdt_descriptionChange11121211,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            border: 2,
                            height: 51,
                            itemId: 'ChartClick',
                            margin: 3,
                            title: 'Выполнить при нажатии на график',
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: 3
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'Edt_func_class_name',
                                    margin: '0 3 3 0',
                                    fieldLabel: 'Класс функций',
                                    labelWidth: 90,
                                    listeners: {
                                        change: {
                                            fn: me.onEdt_descriptionChange11111_111,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'Edt_func_name',
                                    margin: '0 3 3 0',
                                    fieldLabel: 'Функция',
                                    labelWidth: 55,
                                    listeners: {
                                        change: {
                                            fn: me.onEdt_descriptionChange11111_1111,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    itemId: 'Edt_param_list',
                                    margin: '0 0 3 0',
                                    width: '',
                                    fieldLabel: 'Параметры',
                                    labelWidth: 70,
                                    emptyText: '{code:\'\',ParamValuesArray:{ModalWindow:true}}',
                                    listeners: {
                                        change: {
                                            fn: me.onEdt_descriptionChange1112122,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    border: 0,
                    title: 'Оси',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            border: 0,
                            margin: 3,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    columnWidth: 0.6,
                                    border: 2,
                                    margin: '0 0 0 3',
                                    title: 'Наименование осей',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 2,
                                            itemId: 'Edt_x_name',
                                            margin: '3 0 3 0',
                                            fieldLabel: 'Ось абсцисс',
                                            labelWidth: 80,
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_descriptionChange11121,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 2,
                                            itemId: 'Edt_y_name',
                                            margin: '3 0 3 0',
                                            fieldLabel: 'Ось ординат',
                                            labelWidth: 80,
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_descriptionChange111211,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: 'column',
                                            items: [
                                                me.processEdt_axes_color({
                                                    xtype: 'triggerfield',
                                                    columnWidth: 0.6,
                                                    itemId: 'Edt_axes_color',
                                                    margin: '3 3 3 0',
                                                    fieldLabel: 'Цвет текста',
                                                    labelWidth: 80,
                                                    emptyText: 'Выбор цвета',
                                                    regex: /^[0-9a-f]{3,6}$/i,
                                                    selectOnFocus: true,
                                                    triggerCls: 'x-form-search-trigger',
                                                    listeners: {
                                                        change: {
                                                            fn: me.onEdt_BackgrColorChange2,
                                                            scope: me
                                                        }
                                                    }
                                                }),
                                                {
                                                    xtype: 'textfield',
                                                    columnWidth: 0.4,
                                                    itemId: 'Edt_axes_font_size',
                                                    margin: '3 0 3 3',
                                                    fieldLabel: 'Размер шрифта',
                                                    labelWidth: 95,
                                                    emptyText: '12px',
                                                    listeners: {
                                                        change: {
                                                            fn: me.onEdt_descriptionChange1112121,
                                                            scope: me
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    columnWidth: 0.4,
                                    border: '2 2 2 0',
                                    margin: '0 3 0 0',
                                    title: 'Подписи осей',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        me.processEdt_label_color({
                                            xtype: 'triggerfield',
                                            itemId: 'Edt_label_color',
                                            margin: '3 3 3 0',
                                            padding: 0,
                                            fieldLabel: 'Цвет текста',
                                            labelWidth: 80,
                                            emptyText: 'Выбор цвета',
                                            regex: /^[0-9a-f]{3,6}$/i,
                                            selectOnFocus: true,
                                            triggerCls: 'x-form-search-trigger',
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_BackgrColorChange1,
                                                    scope: me
                                                }
                                            }
                                        }),
                                        {
                                            xtype: 'textfield',
                                            itemId: 'Edt_axes_label_font_size',
                                            margin: '3 3 3 0',
                                            fieldLabel: 'Размер шрифта',
                                            labelWidth: 95,
                                            emptyText: '12px',
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_descriptionChange11121212,
                                                    scope: me
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'Edt_label_rotate',
                                            margin: '3 0 1 0',
                                            fieldLabel: 'Угол поворота',
                                            labelWidth: 90,
                                            inputType: 'number',
                                            listeners: {
                                                change: {
                                                    fn: me.onEdt_descriptionChange111,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'checkboxgroup',
                            margin: '3 200 3 10',
                            maxWidth: 370,
                            fieldLabel: 'Показать сетку',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    itemId: 'ChkShowGrid_y',
                                    margin: '0 3 3 3',
                                    fieldLabel: '',
                                    boxLabel: 'Для оси абсцисс',
                                    listeners: {
                                        change: {
                                            fn: me.onChkShowErrorChange11,
                                            scope: me
                                        }
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    itemId: 'ChkShowGrid_x',
                                    margin: '0 3 3 6',
                                    width: '',
                                    fieldLabel: '',
                                    boxLabel: 'Для оси ординат',
                                    listeners: {
                                        change: {
                                            fn: me.onChkShowErrorChange1,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: '',
                    itemId: 'legend',
                    layout: 'column',
                    title: 'Легенда',
                    items: [
                        {
                            xtype: 'combobox',
                            columnWidth: 0.25,
                            itemId: 'Edt_legend_position',
                            margin: '3 3 3 6',
                            fieldLabel: 'Положение',
                            labelWidth: 70,
                            editable: false,
                            displayField: 'name',
                            store: [
                                [
                                    '0',
                                    'Не показывать'
                                ],
                                [
                                    '1',
                                    'Внизу'
                                ],
                                [
                                    '2',
                                    'Слева'
                                ],
                                [
                                    '3',
                                    'Справа'
                                ],
                                [
                                    '4',
                                    'Сверху'
                                ]
                            ],
                            valueField: 'id',
                            listeners: {
                                change: {
                                    fn: me.onEdt_descriptionChange11111_11,
                                    scope: me
                                }
                            }
                        },
                        me.processEdt_legend_box_color({
                            xtype: 'triggerfield',
                            columnWidth: 0.25,
                            itemId: 'Edt_legend_box_color',
                            margin: 3,
                            padding: 0,
                            fieldLabel: 'Цвет фона',
                            labelWidth: 70,
                            emptyText: 'Выбор цвета',
                            regex: /^[0-9a-f]{3,6}$/i,
                            selectOnFocus: true,
                            triggerCls: 'x-form-search-trigger',
                            listeners: {
                                change: {
                                    fn: me.onEdt_BackgrColorChange11,
                                    scope: me
                                }
                            }
                        }),
                        me.processEdt_legend_label_color({
                            xtype: 'triggerfield',
                            columnWidth: 0.25,
                            itemId: 'Edt_legend_label_color',
                            margin: 3,
                            padding: 0,
                            fieldLabel: 'Цвет текста',
                            labelWidth: 80,
                            emptyText: 'Выбор цвета',
                            regex: /^[0-9a-f]{3,6}$/i,
                            selectOnFocus: true,
                            triggerCls: 'x-form-search-trigger',
                            listeners: {
                                change: {
                                    fn: me.onEdt_BackgrColorChange112,
                                    scope: me
                                }
                            }
                        }),
                        {
                            xtype: 'textfield',
                            columnWidth: 0.25,
                            itemId: 'Edt_legend_font_size',
                            margin: 3,
                            fieldLabel: 'Размер шрифта',
                            emptyText: '12px',
                            listeners: {
                                change: {
                                    fn: me.onEdt_descriptionChange111212,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'checkboxgroup',
                    margin: '3 3 0 6',
                    maxWidth: 650,
                    fieldLabel: 'Вывод сообщений',
                    labelWidth: 110,
                    items: [
                        {
                            xtype: 'checkboxfield',
                            itemId: 'ChkShowError',
                            fieldLabel: '',
                            boxLabel: 'Об ошибке выполнения запроса',
                            listeners: {
                                change: {
                                    fn: me.onChkShowErrorChange,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'checkboxfield',
                            itemId: 'ChkShowEmptyMessage',
                            fieldLabel: '',
                            boxLabel: 'О пустом результате выполнения запроса',
                            listeners: {
                                change: {
                                    fn: me.onChkShowEmptyMessageChange,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processEdt_header_fill_color: function(config) {
        config.onTriggerClick = function (evnt) {
            if(this.disabled){
                return;
            }
            var me = this;
            this.menu = new Ext.menu.ColorPicker({
                shadow: true,
                autoShow : true,
                listeners: {
                    scope:this,
                    select: function(field, value, opts){
                        me.setValue(value);
                        me.inputEl.setStyle({backgroundColor: '#' +me.getValue(), backgroundImage: 'none',color:'#' +invert(me.getValue())});
                        me.menu.hide();
                    },
                    show: function(field,opts){
                        field.getEl().monitorMouseLeave(500, field.hide, field);
                    }
                }
            });
            this.menu.alignTo(this.inputEl, 'tl-bl?');
            this.menu.doLayout();

            this.menu.on(Ext.apply({}, this.menuListeners, {
                scope:this
            }));

            this.menu.show(this.inputEl);

        };
        return config;
    },

    processEdt_header_text_color: function(config) {
        config.onTriggerClick = function (evnt) {
            if(this.disabled){
                return;
            }
            var me = this;
            this.menu = new Ext.menu.ColorPicker({
                shadow: true,
                autoShow : true,
                listeners: {
                    scope:this,
                    select: function(field, value, opts){
                        me.setValue(value);
                        me.inputEl.setStyle({backgroundColor: '#' +me.getValue(), backgroundImage: 'none',color:'#' +invert(me.getValue())});
                        me.menu.hide();
                    },
                    show: function(field,opts){
                        field.getEl().monitorMouseLeave(500, field.hide, field);
                    }
                }
            });
            this.menu.alignTo(this.inputEl, 'tl-bl?');
            this.menu.doLayout();

            this.menu.on(Ext.apply({}, this.menuListeners, {
                scope:this
            }));

            this.menu.show(this.inputEl);

        };
        return config;
    },

    processEdt_bg_color: function(config) {
        config.onTriggerClick = function (evnt) {
            if(this.disabled){
                return;
            }
            var me = this;
            this.menu = new Ext.menu.ColorPicker({
                shadow: true,
                autoShow : true,
                listeners: {
                    scope:this,
                    select: function(field, value, opts){
                        me.setValue(value);
                        me.inputEl.setStyle({backgroundColor: '#' +me.getValue(), backgroundImage: 'none',color:'#' +invert(me.getValue())});
                        me.menu.hide();
                    },
                    show: function(field,opts){
                        field.getEl().monitorMouseLeave(500, field.hide, field);
                    }
                }
            });
            this.menu.alignTo(this.inputEl, 'tl-bl?');
            this.menu.doLayout();

            this.menu.on(Ext.apply({}, this.menuListeners, {
                scope:this
            }));

            this.menu.show(this.inputEl);

        };
        return config;
    },

    processEdt_info_label_color: function(config) {
        config.onTriggerClick = function (evnt) {
            if(this.disabled){
                return;
            }
            var me = this;
            this.menu = new Ext.menu.ColorPicker({
                shadow: true,
                autoShow : true,
                listeners: {
                    scope:this,
                    select: function(field, value, opts){
                        me.setValue(value);
                        me.inputEl.setStyle({backgroundColor: '#' +me.getValue(), backgroundImage: 'none',color:'#' +invert(me.getValue())});
                        me.menu.hide();
                    },
                    show: function(field,opts){
                        field.getEl().monitorMouseLeave(500, field.hide, field);
                    }
                }
            });
            this.menu.alignTo(this.inputEl, 'tl-bl?');
            this.menu.doLayout();

            this.menu.on(Ext.apply({}, this.menuListeners, {
                scope:this
            }));

            this.menu.show(this.inputEl);

        };
        return config;
    },

    processEdt_axes_color: function(config) {
        config.onTriggerClick = function (evnt) {
            if(this.disabled){
                return;
            }
            var me = this;
            this.menu = new Ext.menu.ColorPicker({
                shadow: true,
                autoShow : true,
                listeners: {
                    scope:this,
                    select: function(field, value, opts){
                        me.setValue(value);
                        me.inputEl.setStyle({backgroundColor: '#' +me.getValue(), backgroundImage: 'none',color:'#' +invert(me.getValue())});
                        me.menu.hide();
                    },
                    show: function(field,opts){
                        field.getEl().monitorMouseLeave(500, field.hide, field);
                    }
                }
            });
            this.menu.alignTo(this.inputEl, 'tl-bl?');
            this.menu.doLayout();

            this.menu.on(Ext.apply({}, this.menuListeners, {
                scope:this
            }));

            this.menu.show(this.inputEl);

        };
        return config;
    },

    processEdt_label_color: function(config) {
        config.onTriggerClick = function (evnt) {
            if(this.disabled){
                return;
            }
            var me = this;
            this.menu = new Ext.menu.ColorPicker({
                shadow: true,
                autoShow : true,
                listeners: {
                    scope:this,
                    select: function(field, value, opts){
                        me.setValue(value);
                        me.inputEl.setStyle({backgroundColor: '#' +me.getValue(), backgroundImage: 'none',color:'#' +invert(me.getValue())});
                        me.menu.hide();
                    },
                    show: function(field,opts){
                        field.getEl().monitorMouseLeave(500, field.hide, field);
                    }
                }
            });
            this.menu.alignTo(this.inputEl, 'tl-bl?');
            this.menu.doLayout();

            this.menu.on(Ext.apply({}, this.menuListeners, {
                scope:this
            }));

            this.menu.show(this.inputEl);

        };
        return config;
    },

    processEdt_legend_box_color: function(config) {
        config.onTriggerClick = function (evnt) {
            if(this.disabled){
                return;
            }
            var me = this;
            this.menu = new Ext.menu.ColorPicker({
                shadow: true,
                autoShow : true,
                listeners: {
                    scope:this,
                    select: function(field, value, opts){
                        me.setValue(value);
                        me.inputEl.setStyle({backgroundColor: '#' +me.getValue(), backgroundImage: 'none',color:'#' +invert(me.getValue())});
                        me.menu.hide();
                    },
                    show: function(field,opts){
                        field.getEl().monitorMouseLeave(500, field.hide, field);
                    }
                }
            });
            this.menu.alignTo(this.inputEl, 'tl-bl?');
            this.menu.doLayout();

            this.menu.on(Ext.apply({}, this.menuListeners, {
                scope:this
            }));

            this.menu.show(this.inputEl);

        };
        return config;
    },

    processEdt_legend_label_color: function(config) {
        config.onTriggerClick = function (evnt) {
            if(this.disabled){
                return;
            }
            var me = this;
            this.menu = new Ext.menu.ColorPicker({
                shadow: true,
                autoShow : true,
                listeners: {
                    scope:this,
                    select: function(field, value, opts){
                        me.setValue(value);
                        me.inputEl.setStyle({backgroundColor: '#' +me.getValue(), backgroundImage: 'none',color:'#' +invert(me.getValue())});
                        me.menu.hide();
                    },
                    show: function(field,opts){
                        field.getEl().monitorMouseLeave(500, field.hide, field);
                    }
                }
            });
            this.menu.alignTo(this.inputEl, 'tl-bl?');
            this.menu.doLayout();

            this.menu.on(Ext.apply({}, this.menuListeners, {
                scope:this
            }));

            this.menu.show(this.inputEl);

        };
        return config;
    },

    onEdt_descriptionChange1: function(field, newValue, oldValue, eOpts) {
        this.rawData.Code=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onEdt_descriptionChange11: function(field, newValue, oldValue, eOpts) {
        this.rawData.code_help=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onEdt_descriptionChange: function(field, newValue, oldValue, eOpts) {
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

        this.rawData.Description=newValue;
        if(this.needUpdateTree==true){
            if(trim(this.rawData.Description)=='')
                this.record.set('text', mainContainer.MICaption_Diagram);
            else
                this.record.set('text', this.rawData.Description);
            this.record.commit();
            this.rawData.text=this.rawData.Description;
        }
    },

    onEdt_BackgrColorChange113: function(field, newValue, oldValue, eOpts) {
                this.rawData.header_fill_color=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_BackgrColorChange1121: function(field, newValue, oldValue, eOpts) {
                this.rawData.header_text_color=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange111212121: function(field, newValue, oldValue, eOpts) {
        this.rawData.header_font_size=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange11121111: function(field, newValue, oldValue, eOpts) {
        this.rawData.diagram_width=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange111211111: function(field, newValue, oldValue, eOpts) {
        this.rawData.diagram_height=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange1111: function(field, newValue, oldValue, eOpts) {
        this.rawData.diagram_type=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange11112: function(field, newValue, oldValue, eOpts) {
        this.rawData.orientation=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_BackgrColorChange: function(field, newValue, oldValue, eOpts) {
                this.rawData.bg_color=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange11111: function(field, newValue, oldValue, eOpts) {
        this.rawData.diagram_theme=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange1112: function(field, newValue, oldValue, eOpts) {
        this.rawData.gutter=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange11122: function(field, newValue, oldValue, eOpts) {
        this.rawData.groupGutter=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange11111_12: function(field, newValue, oldValue, eOpts) {
        this.rawData.label_display=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange11111_1: function(field, newValue, oldValue, eOpts) {
        this.rawData.label_type_visible=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_BackgrColorChange111: function(field, newValue, oldValue, eOpts) {
                this.rawData.info_label_color=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange11121211: function(field, newValue, oldValue, eOpts) {
        this.rawData.label_font_size=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange11111_111: function(field, newValue, oldValue, eOpts) {
        this.rawData.func_class_name=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange11111_1111: function(field, newValue, oldValue, eOpts) {
        this.rawData.func_name=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange1112122: function(field, newValue, oldValue, eOpts) {
        this.rawData.param_list=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange11121: function(field, newValue, oldValue, eOpts) {
        this.rawData.x_name=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;

    },

    onEdt_descriptionChange111211: function(field, newValue, oldValue, eOpts) {
        this.rawData.y_name=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onEdt_BackgrColorChange2: function(field, newValue, oldValue, eOpts) {
                this.rawData.axes_color=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onEdt_descriptionChange1112121: function(field, newValue, oldValue, eOpts) {
        this.rawData.axes_font_size=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onEdt_BackgrColorChange1: function(field, newValue, oldValue, eOpts) {
                this.rawData.label_color=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onEdt_descriptionChange11121212: function(field, newValue, oldValue, eOpts) {
        this.rawData.axes_label_font_size=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onEdt_descriptionChange111: function(field, newValue, oldValue, eOpts) {
        this.rawData.label_rotate=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onChkShowErrorChange11: function(field, newValue, oldValue, eOpts) {
        this.rawData.ShowGrid_y=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onChkShowErrorChange1: function(field, newValue, oldValue, eOpts) {
        this.rawData.ShowGrid_x=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onEdt_descriptionChange11111_11: function(field, newValue, oldValue, eOpts) {
        this.rawData.legend_position=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onEdt_BackgrColorChange11: function(field, newValue, oldValue, eOpts) {
                this.rawData.legend_box_color=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onEdt_BackgrColorChange112: function(field, newValue, oldValue, eOpts) {
                this.rawData.legend_label_color=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onEdt_descriptionChange111212: function(field, newValue, oldValue, eOpts) {
        this.rawData.legend_font_size=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onChkShowErrorChange: function(field, newValue, oldValue, eOpts) {
        this.rawData.ShowError=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    onChkShowEmptyMessageChange: function(field, newValue, oldValue, eOpts) {
        this.rawData.ShowEmptyMessage=newValue;
        var mainContainer = field.ownerCt.findParentByType('#DesignDiagramMainContainer');
        mainContainer.modified=true;
    },

    LoadNodeValues: function(rawData, record) {
        this.needUpdateTree=false; //нужно для отключения переписывания текста в дереве при присвоении значений текста
        this.rawData=rawData;
        this.record = record;
        this.down('#Edt_Code').setValue(rawData.Code);
        this.down('#Edt_description').setValue(rawData.Description);
        this.down('#Edt_code_help').setValue(rawData.code_help);
        this.down('#Edt_label_rotate').setValue(rawData.label_rotate);
        this.down('#Edt_label_type_visible').setValue(rawData.label_type_visible);
        this.down('#Edt_legend_position').setValue(rawData.legend_position);
        this.down('#Edt_legend_font_size').setValue(rawData.legend_font_size);
        this.down('#Edt_diagram_type').setValue(rawData.diagram_type);
        //this.down('#Edt_bg_color').setValue(rawData.bg_color);
        var _color=this.down('#Edt_bg_color');
        _color.setValue(rawData.bg_color);
        _color.setFieldStyle({backgroundColor: '#' +_color.getValue(), backgroundImage: 'none',color:'#' +invert(_color.getValue())});
        //_color.inputEl.setStyle({backgroundColor: '#' +_color.getValue(), backgroundImage: 'none'});

        this.down('#Edt_orientation').setValue(rawData.orientation);
        this.down('#Edt_x_name').setValue(rawData.x_name);
        this.down('#Edt_y_name').setValue(rawData.y_name);
        this.down('#Edt_axes_font_size').setValue(rawData.axes_font_size);
        this.down('#Edt_axes_label_font_size').setValue(rawData.axes_label_font_size);
        this.down('#Edt_label_font_size').setValue(rawData.label_font_size);
        //this.down('#Edt_label_color').setValue(rawData.label_color);
        _color=this.down('#Edt_label_color');
        _color.setValue(rawData.label_color);
        _color.setFieldStyle({backgroundColor: '#' +_color.getValue(), backgroundImage: 'none',color:'#' +invert(_color.getValue())});


        //this.down('#Edt_info_label_color').setValue(rawData.info_label_color);
        _color=this.down('#Edt_info_label_color');
        _color.setValue(rawData.info_label_color);
        _color.setFieldStyle({backgroundColor: '#' +_color.getValue(), backgroundImage: 'none',color:'#' +invert(_color.getValue())});

        //this.down('#Edt_axes_color').setValue(rawData.axes_color);
        _color=this.down('#Edt_axes_color');
        _color.setValue(rawData.axes_color);
        _color.setFieldStyle({backgroundColor: '#' +_color.getValue(), backgroundImage: 'none',color:'#' +invert(_color.getValue())});

        this.down('#Edt_label_display').setValue(rawData.label_display);

        //this.down('#Edt_legend_box_color').setValue(rawData.legend_box_color);
        _color=this.down('#Edt_legend_box_color');
        _color.setValue(rawData.legend_box_color);
        _color.setFieldStyle({backgroundColor: '#' +_color.getValue(), backgroundImage: 'none',color:'#' +invert(_color.getValue())});

        //this.down('#Edt_legend_label_color').setValue(rawData.legend_label_color);
        _color=this.down('#Edt_legend_label_color');
        _color.setValue(rawData.legend_label_color);
        _color.setFieldStyle({backgroundColor: '#' +_color.getValue(), backgroundImage: 'none',color:'#' +invert(_color.getValue())});

        //this.down('#Edt_axes_color').setValue(rawData.axes_color);
        _color=this.down('#Edt_axes_color');
        _color.setValue(rawData.axes_color);
        _color.setFieldStyle({backgroundColor: '#' +_color.getValue(), backgroundImage: 'none',color:'#' +invert(_color.getValue())});

        this.down('#Edt_groupGutter').setValue(rawData.groupGutter);
        this.down('#Edt_gutter').setValue(rawData.gutter);

        this.down('#ChkShowGrid_x').setValue(rawData.ShowGrid_x);
        this.down('#ChkShowGrid_y').setValue(rawData.ShowGrid_y);

        //this.down('#Edt_header_text_color').setValue(rawData.header_text_color);
        _color=this.down('#Edt_header_text_color');
        _color.setValue(rawData.header_text_color);
        _color.setFieldStyle({backgroundColor: '#' +_color.getValue(), backgroundImage: 'none',color:'#' +invert(_color.getValue())});

        //this.down('#Edt_header_fill_color').setValue(rawData.header_fill_color);
        _color=this.down('#Edt_header_fill_color');
        _color.setValue(rawData.header_fill_color);
        _color.setFieldStyle({backgroundColor: '#' +_color.getValue(), backgroundImage: 'none',color:'#' +invert(_color.getValue())});

        this.down('#Edt_header_font_size').setValue(rawData.header_font_size);

        this.down('#Edt_func_class_name').setValue(rawData.func_class_name);
        this.down('#Edt_func_name').setValue(rawData.func_name);
        this.down('#Edt_param_list').setValue(rawData.param_list);


        this.down('#Edt_diagram_width').setValue(rawData.diagram_width);
        this.down('#Edt_diagram_height').setValue(rawData.diagram_height);
        this.down('#ChkShowError').setValue(rawData.ShowError);

        this.down('#ChkShowEmptyMessage').setValue(rawData.ShowEmptyMessage);
        this.needUpdateTree=true;

    }

});