/*
 * File: app/view/DesignReportMainContainer.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Report.view.DesignReportMainContainer', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.tree.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.toolbar.Spacer',
        'Ext.toolbar.Separator',
        'Ext.tree.View'
    ],

    height: 513,
    itemId: 'DesignReportMainContainer',
    width: 793,
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'treepanel',
                    region: 'west',
                    itemId: 'StructureTree',
                    width: 255,
                    title: 'Структура',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            itemId: 'StructureToolBar',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'BtnAdd',
                                    iconCls: 'cls_add',
                                    text: '',
                                    tooltip: 'Добавить',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    var StructureTree= item. findParentByType('#DesignReportMainContainer').down('#StructureTree') ;
                                                    var RootNode= StructureTree.getRootNode();
                                                    if(RootNode!= undefined){
                                                        RootNode.appendChild({text: item.text, expanded: true, leaf:false,children: [], ItemType: 'paragraph', iconCls: 'paragraph',
                                                        TextAlignment: 'RB_LEFT', LeftMargin: 0, RightMargin: 0, TextIdent: 2, ShowError: true});}
                                                },
                                                iconCls: 'cls_paragraf',
                                                text: 'Абзац',
                                                menu: {
                                                    xtype: 'menu',
                                                    width: '',
                                                    items: [
                                                        {
                                                            xtype: 'menuitem',
                                                            handler: function(item, e) {
                                                                var StructureTree= item. findParentByType('#DesignReportMainContainer').down('#StructureTree') ;
                                                                var Node= StructureTree.getSelectionModel().getSelection();
                                                                if(Node!= undefined){
                                                                    Node=Node[0];
                                                                    if((Node!= undefined)&&(Node.raw.ItemType== 'paragraph')){
                                                                        Node.appendChild({text: item.text, leaf:true,  ItemType: 'text', iconCls: 'text',
                                                                        DataSource: 'RB_Text'});
                                                                    }}
                                                            },
                                                            disabled: true,
                                                            itemId: 'MI_text',
                                                            text: 'Блок текста'
                                                        },
                                                        {
                                                            xtype: 'menuitem',
                                                            handler: function(item, e) {
                                                                var StructureTree= item. findParentByType('#DesignReportMainContainer').down('#StructureTree') ;
                                                                var Node= StructureTree.getSelectionModel().getSelection();
                                                                if(Node!= undefined){
                                                                    Node=Node[0];
                                                                    if((Node!= undefined)&&(Node.raw.ItemType== 'paragraph')){
                                                                        Node.appendChild({text: item.text, leaf:true,  ItemType: 'hyperlink', iconCls: 'hyperlink',
                                                                            DataSource: 'RB_Text',
                                                                        LinkText:'', LinkURL:'', DBLinkText:'', DBLinkURL:''});
                                                                    }}
                                                            },
                                                            disabled: true,
                                                            itemId: 'MI_hyperlink',
                                                            text: 'Гиперссылка'
                                                        },
                                                        {
                                                            xtype: 'menuitem',
                                                            handler: function(item, e) {
                                                                var StructureTree= item. findParentByType('#DesignReportMainContainer').down('#StructureTree') ;
                                                                var Node= StructureTree.getSelectionModel().getSelection();
                                                                if(Node!= undefined){
                                                                    Node=Node[0];
                                                                    if((Node!= undefined)&&(Node.raw.ItemType== 'paragraph')){
                                                                        Node.appendChild({text: item.text, leaf:true,  ItemType: 'image', iconCls: 'image',
                                                                        imgHeight: 20, imgWidth: 20, DataSource: 'RB_Text', ImagePath:'', DataField:''});
                                                                    }}
                                                            },
                                                            disabled: true,
                                                            itemId: 'MI_images',
                                                            text: 'Графический элемент'
                                                        },
                                                        {
                                                            xtype: 'menuitem',
                                                            handler: function(item, e) {
                                                                var StructureTree= item. findParentByType('#DesignReportMainContainer').down('#StructureTree') ;
                                                                var Node= StructureTree.getSelectionModel().getSelection();
                                                                if(Node!= undefined){
                                                                    Node=Node[0];
                                                                    if((Node!= undefined)&&(Node.raw.ItemType== 'paragraph')){
                                                                        Node.appendChild({text: item.text, leaf:true,  ItemType: 'linebreak', iconCls: 'linebreak'});
                                                                    }}
                                                            },
                                                            disabled: true,
                                                            itemId: 'MI_linebreak',
                                                            text: 'Разрыв строки'
                                                        }
                                                    ]
                                                }
                                            },
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    var StructureTree= item. findParentByType('#DesignReportMainContainer').down('#StructureTree') ;
                                                    var RootNode= StructureTree.getRootNode();
                                                    var tblWidth=RootNode.raw.PageSizeWidth- RootNode.raw.MarginLeft- RootNode.raw.MarginRight;
                                                    if(RootNode!== undefined){
                                                        var TableNode=RootNode.appendChild({text: item.text, expanded: true, leaf:false,children: [], ItemType: 'table', iconCls: 'table',
                                                            TabelWidth: tblWidth, TableAlignment: 'RB_LEFT', HeaderHeight: 4});
                                                    }
                                                },
                                                iconCls: 'cls_table',
                                                text: 'Таблица',
                                                menu: {
                                                    xtype: 'menu',
                                                    itemId: 'TableMenu',
                                                    width: 80,
                                                    items: [
                                                        {
                                                            xtype: 'menuitem',
                                                            handler: function(item, e) {
                                                                var StructureTree= item. findParentByType('#DesignReportMainContainer').down('#StructureTree') ;
                                                                var Node= StructureTree.getSelectionModel().getSelection();
                                                                if(Node!== undefined){
                                                                    Node=Node[0];
                                                                    if((Node!== undefined)&&(Node.raw.ItemType== 'table')){
                                                                        Node.appendChild({text: item.text, leaf:true,  ItemType: 'tableColumn', iconCls: 'tableColumn'});
                                                                    }}
                                                            },
                                                            disabled: true,
                                                            itemId: 'MI_tableColumn',
                                                            iconCls: 'cls_table_column',
                                                            text: 'Столбец'
                                                        }
                                                    ]
                                                }
                                            },
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    var StructureTree= item. findParentByType('#DesignReportMainContainer').down('#StructureTree') ;
                                                    var RootNode= StructureTree.getRootNode();
                                                    if(RootNode!= undefined){
                                                        RootNode.appendChild({text: item.text, expanded: true, leaf:false,children: [], ItemType: 'list', iconCls: 'list',
                                                        DataSource: 'RB_Text'});}
                                                },
                                                iconCls: 'cls_list',
                                                text: 'Список'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    var StructureTree= item. findParentByType('#DesignReportMainContainer').down('#StructureTree') ;
                                                    var RootNode= StructureTree.getRootNode();
                                                    if(RootNode!= undefined){
                                                        var w=  Ext.create("Report.view.SelectReportTemplateWindow", {});
                                                        w.addEvents('BtnOk');
                                                        w.show();
                                                        w.addListener('BtnOk', function(Template_Code, Template_Descr) {
                                                            RootNode.appendChild({text: item.text, expanded: true, leaf:false,children: [],iconCls:'embedded_report',
                                                                ItemType: 'embedded_report',
                                                            Template_Code:Template_Code, Template_Descr: Template_Descr});
                                                            CloseWindow(w);
                                                        });
                                                    };
                                                },
                                                iconCls: 'cls_report_report',
                                                text: 'Отчет'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var StructureTree= button. findParentByType('#DesignReportMainContainer').down('#StructureTree') ;
                                        var Node= StructureTree.getSelectionModel().getSelection();
                                        if(Node!= undefined){
                                            Node=Node[0];
                                            if((Node!= undefined)&&(Node!=StructureTree.getRootNode())){
                                                Node.removeAll(true);
                                                Node.remove(true);
                                                StructureTree.store.sync();
                                            }}
                                    },
                                    disabled: true,
                                    itemId: 'BtnDel',
                                    iconCls: 'cls_del',
                                    text: '',
                                    tooltip: 'Удалить'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var mainContainer= button.findParentByType('#DesignReportMainContainer');
                                        var BtnCopy= mainContainer.down('#BtnCopy') ;
                                        var BtnDel= mainContainer.down('#BtnDel') ;
                                        if(BtnCopy.handler(button)==true){
                                            BtnDel.handler(button);
                                        }
                                    },
                                    disabled: true,
                                    itemId: 'BtnCut',
                                    iconCls: 'cls_cut',
                                    text: '',
                                    tooltip: 'Вырезать'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        function GetConfObj(Node){
                                            var result= CopyObjectProps(Node.raw);
                                            if(Node.hasChildNodes( )==true){
                                                result.children= [];
                                                Ext.each(Node.childNodes, function (Child) {
                                                    var itm= GetConfObj(Child);
                                                    result.children.push(itm);
                                                });
                                            }else result.children=null;
                                            return result;
                                        }

                                        var mainContainer= button.findParentByType('#DesignReportMainContainer');
                                        var StructureTree= mainContainer.down('#StructureTree') ;
                                        var Node= StructureTree.getSelectionModel().getSelection();
                                        if(Node!= undefined){
                                            Node=Node[0];
                                            if((Node!= undefined)&&(Node!=StructureTree.getRootNode())){
                                                Ext.destroy(mainContainer.ClipboardItem);
                                                mainContainer.ClipboardItem=null;
                                                mainContainer.ClipboardItem=GetConfObj(Node);
                                                mainContainer.down('#ClipboardContentsTxt').setText('В буфере: '+mainContainer.ClipboardItem.text);
                                                return true;
                                            }}
                                    },
                                    disabled: true,
                                    itemId: 'BtnCopy',
                                    iconCls: 'cls_copy',
                                    text: '',
                                    tooltip: 'Копировать'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var NodeToInsert, IndexInsert;
                                        var mainContainer= button.findParentByType('#DesignReportMainContainer');
                                        var StructureTree= mainContainer.down('#StructureTree') ;
                                        var Node= StructureTree.getSelectionModel().getSelection();
                                        if(Node!= undefined){
                                            Node=Node[0];
                                            if((Node!= undefined)){
                                                if((mainContainer.ClipboardItem.ItemType=='embedded_report')||
                                                (mainContainer.ClipboardItem.ItemType=='paragraph')||
                                                (mainContainer.ClipboardItem.ItemType=='table')||
                                                (mainContainer.ClipboardItem.ItemType=='list')){
                                                    NodeToInsert= StructureTree.getRootNode();
                                                    if(Node!=StructureTree.getRootNode())
                                                    IndexInsert =Node.parentNode.indexOf(Node)+1;
                                                    else IndexInsert=0;
                                                }else
                                                if((mainContainer.ClipboardItem.ItemType=='text')||
                                                (mainContainer.ClipboardItem.ItemType=='hyperlink')||
                                                (mainContainer.ClipboardItem.ItemType=='image')||
                                                (mainContainer.ClipboardItem.ItemType=='linebreak')){
                                                    if(Node.raw.ItemType=='paragraph') {
                                                        IndexInsert=0;
                                                        NodeToInsert=Node;
                                                    } else if((Node.raw.ItemType=='text')||
                                                    (Node.raw.ItemType=='hyperlink')||
                                                    (Node.raw.ItemType=='image')||
                                                    (Node.raw.ItemType=='linebreak')){
                                                        IndexInsert =Node.parentNode.indexOf(Node)+1;
                                                        NodeToInsert=Node.parentNode;
                                                    }else
                                                    return;
                                                }else
                                                return;
                                                var ConfObj= CopyObjectProps(mainContainer.ClipboardItem);
                                                ConfObj.expanded=false;
                                                NodeToInsert.insertChild(IndexInsert, ConfObj);
                                            }else
                                            return;
                                        }
                                    },
                                    disabled: true,
                                    itemId: 'BtnPaste',
                                    iconCls: 'cls_paste',
                                    text: '',
                                    tooltip: 'Вставить'
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 5
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 5
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var mainContainer = button.findParentByType('#DesignReportMainContainer');
                                        var report_PropertyForm=mainContainer.ArrayOfReportObjectTypes.report;
                                        var w=  Ext.create("Params.view.EditParams", {Params: report_PropertyForm.rawData.ReportParams});
                                        w.mainContainer= mainContainer;
                                        w.addEvents('BtnOk');
                                        w.show();
                                        w.addListener('BtnOk', function(ReportParams) {
                                            report_PropertyForm.rawData.ReportParams=ReportParams;
                                            CloseWindow(w);
                                        });

                                    },
                                    itemId: 'BtnEdtParam',
                                    iconCls: 'cls_params',
                                    text: '',
                                    tooltip: 'Редактор параметров'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var mainContainer = button.findParentByType('#DesignReportMainContainer');
                                        var w=  Ext.create("Report.view.EditReportStylesWindow", {});
                                        w.mainContainer= mainContainer;
                                        w.show();
                                    },
                                    itemId: 'BtnEdtStyle',
                                    iconCls: 'cls_edt_css',
                                    text: '',
                                    tooltip: 'Конструктор стилей'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var mainContainer= button.findParentByType('#DesignReportMainContainer');
                                        if (!mainContainer.isNew)
                                        {
                                            mainContainer.SaveReportTemplate();
                                            ComposeODTReportByTemplateInteractiveParamInput(
                                            {code:mainContainer.codeReportTemplate,
                                                ParamValuesArray:{}
                                            });
                                        }else
                                        {Ext.MessageBox.alert('Ошибка сохранения','Сначала надо сохранить шаблон');}
                                    },
                                    hidden: true,
                                    itemId: 'BtnPreview1',
                                    iconCls: 'cls_preview',
                                    text: '',
                                    tooltip: 'Предпросмотр'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'BtnPreview',
                                    iconCls: 'cls_preview',
                                    text: '',
                                    tooltip: 'Предпросмотр',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    var mainContainer= item.findParentByType('#DesignReportMainContainer');
                                                    if (!mainContainer.isNew)
                                                    {
                                                        mainContainer.SaveReportTemplate();
                                                        mainContainer.ReportObject.ComposeReportByTemplateInteractiveParamInput(null,
                                                        {param_list:{code:mainContainer.codeReportTemplate,
                                                            ParamValuesArray:{}
                                                        }});
                                                    }else
                                                    {Ext.MessageBox.alert('Ошибка сохранения','Сначала надо сохранить шаблон');}
                                                },
                                                iconCls: 'cls_preview_odt',
                                                text: 'Отчет'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    var mainContainer= item.findParentByType('#DesignReportMainContainer');
                                                    if (!mainContainer.isNew)
                                                    {
                                                        mainContainer.SaveReportTemplate();
                                                        mainContainer.ReportObject.ComposePDFReportByTemplateInteractiveParamInput(null,
                                                        {param_list:{code:mainContainer.codeReportTemplate,
                                                            ParamValuesArray:{}
                                                        }});
                                                    }else
                                                    {Ext.MessageBox.alert('Ошибка сохранения','Сначала надо сохранить шаблон');}
                                                },
                                                iconCls: 'cls_preview_pdf',
                                                text: 'Отчет PDF'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                handler: function(item, e) {
                                                    var mainContainer= item.findParentByType('#DesignReportMainContainer');
                                                    if (!mainContainer.isNew)
                                                    {
                                                        mainContainer.SaveReportTemplate();
                                                        mainContainer.ReportObject.ComposeHTMLReportByTemplateInteractiveParamInput(null,
                                                        {param_list:{code:mainContainer.codeReportTemplate,
                                                            ParamValuesArray:{}
                                                        }});
                                                    }else
                                                    {Ext.MessageBox.alert('Ошибка сохранения','Сначала надо сохранить шаблон');}
                                                },
                                                iconCls: 'cls_preview_html',
                                                text: 'Отчет HTML'
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ],
                    viewConfig: {
                        autoScroll: true
                    },
                    listeners: {
                        afterrender: {
                            fn: me.onStructureTreeAfterRender,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'PropPanel',
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'PropertyContainer',
                            layout: 'fit',
                            header: false,
                            title: 'Свойства'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onStructureTreeAfterRender: function(component, eOpts) {
        component.getView().select(component.getRootNode());
    },

    SaveReportTemplate: function() {
        var mainContainer= this;//button. findParentByType('#DesignReportMainContainer');
        var StructureTree= mainContainer.down('#StructureTree') ;
        var RootNode= StructureTree.getRootNode();
        if(RootNode!= undefined){
            var Template=mainContainer.ReportObject.SaveReportNodeToJson(RootNode);
            Ext.MessageBox.wait({
                msg: 'Выполняется операция. Ждите...',
                width: 300,
                wait: true,
                waitConfig: {interval: 100}
            });

            var StructureTree= mainContainer.down('#StructureTree') ;
            var RootNode= StructureTree.getRootNode();
            Template.id_report_template=RootNode.raw.id_report_template;

            Report_class.SaveReportTemplate(Template,function(response, options) {
                Ext.MessageBox.hide();
                var result = response;
                if ((result.success === false) && (result.result == 're_connect')) {
                    Ext.MessageBox.alert('Подключение',result.msg);
                    window.onbeforeunload = null;
                    findFirstWindow().window.location.href = __first_page;
                    return;
                }
                if (result.success) {
                    if((mainContainer.grid_ListReportTemplate)&&(mainContainer.grid_ListReportTemplate!=undefined)&&
                       (mainContainer.grid_ListReportTemplate!=null)){
                        mainContainer.grid_ListReportTemplate.getStore().load();
                    }
                    var mainWindow=mainContainer.up('window');
                    mainWindow.Saved=true;
                    if (result.result.id_report_template!=undefined) {
                        var StructureTree= mainContainer.down('#StructureTree') ;
                        var RootNode= StructureTree.getRootNode();
                        RootNode.raw.id_report_template = result.result.id_report_template;
                    }

                    mainContainer.isNew=false;
                    mainContainer.codeReportTemplate=Template.Code;
                    Ext.MessageBox.alert("Результат выполнения ", result.msg);
                } else {
                    Ext.MessageBox.alert("Ошибка сохранения: " , result.msg);
                }

            });
        }
    }

});