/*
 * File: app/view/embedded_report_PropertyForm.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Report.view.embedded_report_PropertyForm', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.form.field.Text',
        'Ext.form.field.Checkbox'
    ],

    height: 133,
    width: 484,
    autoScroll: true,
    bodyPadding: 10,
    title: 'Свойства вложенного отчета',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'EdtDescr',
                    fieldLabel: 'Описание',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    itemId: 'EdtCode',
                    fieldLabel: 'Код',
                    readOnly: true
                },
                {
                    xtype: 'checkboxfield',
                    itemId: 'ChkShowError',
                    fieldLabel: '',
                    boxLabel: 'Выводить сообщение об ошибке формирования',
                    listeners: {
                        change: {
                            fn: me.onChkShowErrorChange1,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onChkShowErrorChange1: function(field, newValue, oldValue, eOpts) {
        this.rawData.ShowError=newValue;
    },

    LoadNodeValues: function(rawData) {
        this.rawData=rawData;
        this.down('#EdtCode').setValue(rawData.Template_Code);
        this.down('#EdtDescr').setValue(rawData.Template_Descr);
        this.down('#ChkShowError').setValue(rawData.ShowError);

    }

});