/*
 * File: app/view/SelectReportTemplateWindow.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Report.view.SelectReportTemplateWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View'
    ],

    height: 325,
    width: 531,
    layout: 'fit',
    title: 'Список шаблонов отчетов',
    maximizable: true,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            disabled: true,
                            itemId: 'BtnSelect',
                            text: 'Выбрать',
                            listeners: {
                                click: {
                                    fn: me.onButtonSelectClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Закрыть',
                            listeners: {
                                click: {
                                    fn: me.onCloseButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    itemId: 'GridListReport',
                    hideHeaders: true,
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'description',
                            text: 'Описание шаблона отчета',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 120,
                            dataIndex: 'code',
                            text: 'Код'
                        }
                    ],
                    listeners: {
                        selectionchange: {
                            fn: me.onGridListReportSelectionChange,
                            scope: me
                        },
                        itemdblclick: {
                            fn: me.onGridListReportItemDblClick,
                            scope: me
                        }
                    }
                }
            ],
            listeners: {
                show: {
                    fn: me.onWindowShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onButtonSelectClick: function(button, e, eOpts) {
        var win=button.findParentByType('window');
        var _grid_ListVisualPanel=win.down('#GridListReport');
        win.fireEvent('BtnOk',
                      _grid_ListVisualPanel.getSelectionModel().getSelection()[0].raw.code,
                     _grid_ListVisualPanel.getSelectionModel().getSelection()[0].raw.description);
    },

    onCloseButtonClick: function(button, e, eOpts) {
        CloseWindow(button.findParentByType('window'));
    },

    onGridListReportSelectionChange: function(model, selected, eOpts) {
        if (selected.length > 0) {
            this.down('#BtnSelect').enable();
        } else {
            this.down('#BtnSelect').disable();
        }
    },

    onGridListReportItemDblClick: function(dataview, record, item, index, e, eOpts) {
         this.onButtonSelectClick(this.down('#BtnSelect'));
    },

    onWindowShow: function(component, eOpts) {
        var store_ListReportTemplate = new Ext.data.Store({
            fields: [{name: 'id_viewpanel', type: 'int'},
              {name: 'description', type: 'string'},
              {name: 'code', type: 'string'}
            ],
            pageSize: 1000000,
            proxy: {
              type: 'direct',
              directFn: 'Report_class.GetListReportTemplate',
              actionMethods: {
                read: 'POST'
              },
              reader: {
                type: 'json',
                root: 'result'
              }
            },
            autoLoad: true});

        this.down('#GridListReport').getView().bindStore(store_ListReportTemplate);
    }

});