/*
 * File: app/view/EditSQLWindow.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SQLEditor.view.EditSQLWindow', {
    extend: 'Ext.container.Container',

    requires: [
        'Ext.form.field.TextArea'
    ],

    height: '',
    id: 'EditSQLWindow',
    itemId: 'EditSQLWindow',
    width: '',
    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textareafield',
                    itemId: 'EdtSQL',
                    fieldLabel: '',
                    hideLabel: true
                }
            ]
        });

        me.callParent(arguments);
    }

});