/*
 * File: app/view/ObjectProperties.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ObjectProperties.view.ObjectProperties', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea'
    ],

    height: 261,
    itemId: 'ObjectProperties',
    width: 490,
    title: 'Объекты (таблицы/ представления)',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    margin: 10,
                    width: 450,
                    fieldLabel: 'Объект для редактирования',
                    labelWidth: 180
                },
                {
                    xtype: 'textareafield',
                    margin: '0 10 10 10',
                    width: 450,
                    fieldLabel: 'Дополнительное условие'
                },
                {
                    xtype: 'textfield',
                    margin: '0 10 10 10',
                    width: 450,
                    fieldLabel: 'Связка для характеризующих полей',
                    labelWidth: 230
                },
                {
                    xtype: 'textfield',
                    margin: '0 10 10 10',
                    width: 450,
                    fieldLabel: 'Код файла помощи',
                    labelWidth: 130
                }
            ]
        });

        me.callParent(arguments);
    }

});