/*
 * File: app/view/ObjectOperationProperties.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ObjectProperties.view.ObjectOperationProperties', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldSet',
        'Ext.form.field.TextArea',
        'Ext.form.field.Checkbox'
    ],

    height: 383,
    width: 491,
    bodyPadding: 10,
    title: 'Операции над объектами',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    fieldLabel: 'Порядковый номер при отображении',
                    labelWidth: 230,
                    allowDecimals: false,
                    allowExponential: false
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    fieldLabel: 'Принадлежность к группе',
                    labelWidth: 160
                },
                {
                    xtype: 'fieldset',
                    title: 'Выполняемая команда',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Код класса',
                            labelWidth: 90
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Код функции',
                            labelWidth: 90
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Параметры',
                            labelWidth: 90
                        }
                    ]
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    fieldLabel: 'Стиль кнопки для вызова операции'
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    boxLabel: 'Доступность при отсутствии данных'
                },
                {
                    xtype: 'checkboxfield',
                    anchor: '100%',
                    boxLabel: 'Является операцией по умолчанию'
                }
            ]
        });

        me.callParent(arguments);
    }

});