/*
 * File: app/view/ReferenceProperties.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ObjectProperties.view.ReferenceProperties', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.field.Number'
    ],

    height: 120,
    width: 400,
    bodyPadding: 10,
    title: 'Связи между объектами',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Наименование'
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    fieldLabel: 'Порядковый номер в списке',
                    labelWidth: 180,
                    allowDecimals: false,
                    allowExponential: false
                }
            ]
        });

        me.callParent(arguments);
    }

});